<?php
    namespace App;
    
    use Illuminate\Support\Str;

    trait BootModel
    {
        protected $guard = ['_id'];
        
        protected static function boot()
        {
            parent::boot(); // TODO: Change the autogenerated stub
            static::creating(function ($q) {
                $q->_id = Str::uuid()->toString();
            });
        }
    }
